website/auth.py
from re import template
from xmlrpc.client import boolean
from flask import Flask, Blueprint, render_template, request, flash, redirect, url_for
from .models import User, Predict
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
import pickle
import numpy as np




app = Flask(__name__)
model = pickle.load(open('model.pkl', 'rb'))

# Define the blueprint of the app
auth = Blueprint('auth', __name__)

@auth.route('/index')
def index():
    return render_template("index.html", user=current_user)

@auth.route('/services')
def services():
    return render_template("services.html", user=current_user)

@auth.route('/about')
def about():
    return render_template("about.html", user=current_user)

@auth.route('/contact')
def contact():
    return render_template("contact.html", user=current_user)

@auth.route('/eligibility', methods=['GET', 'POST'])
@login_required
def eligibility():
    form = Predict()
    return render_template("eligibility.html", user=current_user)

    

@auth.route('/predict', methods=['GET', 'POST'])
@login_required
def predict():
    if request.method ==  'POST':
        gender = request.form['gender']
        married = request.form['married']
        dependents = request.form['dependents']
        education = request.form['education']
        employed = request.form['employed']
        credit = float(request.form['credit'])
        area = request.form['area']
        ApplicantIncome = float(request.form['ApplicantIncome'])
        CoapplicantIncome = float(request.form['CoapplicantIncome'])
        LoanAmount = float(request.form['LoanAmount'])
        Loan_Amount_Term = float(request.form['Loan_Amount_Term'])

        new_form = Predict(gender=gender, married=married, dependents=dependents, education=education, employed=employed, credit=credit, area=area, applicantincome=ApplicantIncome, coapplicantincome=CoapplicantIncome, loanamount=LoanAmount, loanamountterm=Loan_Amount_Term)
        db.session.add(new_form)
        db.session.commit()
        

        # gender
        if (gender == "Male"):
            male=1
        else:
            male=0
        
        # married
        if(married=="Yes"):
            married_yes = 1
        else:
            married_yes=0

        # dependents
        if(dependents=='1'):
            dependents_1 = 1
            dependents_2 = 0
            dependents_3 = 0
        elif(dependents == '2'):
            dependents_1 = 0
            dependents_2 = 1
            dependents_3 = 0
        elif(dependents=="3+"):
            dependents_1 = 0
            dependents_2 = 0
            dependents_3 = 1
        else:
            dependents_1 = 0
            dependents_2 = 0
            dependents_3 = 0  

        # education
        if (education=="Not Graduate"):
            not_graduate=1
        else:
            not_graduate=0

        # employed
        if (employed == "Yes"):
            employed_yes=1
        else:
            employed_yes=0

        # property area

        if(area=="Semiurban"):
            semiurban=1
            urban=0
        elif(area=="Urban"):
            semiurban=0
            urban=1
        else:
            semiurban=0
            urban=0


        ApplicantIncomelog = np.log(ApplicantIncome)
        totalincomelog = np.log(ApplicantIncome+CoapplicantIncome)
        LoanAmountlog = np.log(LoanAmount)
        Loan_Amount_Termlog = np.log(Loan_Amount_Term)

        prediction = model.predict([[credit, ApplicantIncomelog,LoanAmountlog, Loan_Amount_Termlog, totalincomelog, male, married_yes, dependents_1, dependents_2, dependents_3, not_graduate, employed_yes,semiurban, urban ]])

        # print(prediction)

        if(prediction=="N"):
            prediction="You are not qualified for a loan"
        else:
            prediction="You are qualified for a loan"


        return render_template("predictionresult.html", prediction_text="{}".format(prediction))

    else:
        return render_template("predictionresult.html")

@auth.route('/loancalc', methods=['GET', 'POST'])
@login_required # Ensure no one can access the logout page unless they are already logged in
def loancalc():
    return render_template("loancalc.html", user=current_user)

@auth.route('/home')
def home():
    return render_template("home.html", user=current_user)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required # Ensure no one can access the logout page unless they are already logged in
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'))
            db.session.add(new_user) # Add a new user to the database
            db.session.commit() # Update the database
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)



website/templates/about.html
<!doctype html>
<html class="no-js" lang="zxx">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Loan Status Prediction </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="manifest" href="site.webmanifest">
		<link rel="shortcut icon" type="image/x-icon" href="static/assets/img/favicon.ico">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

		<!-- CSS here -->
            <link rel="stylesheet" href="static/assets/css/bootstrap.min.css">
            <link rel="stylesheet" href="static/assets/css/owl.carousel.min.css">
            <link rel="stylesheet" href="static/assets/css/slicknav.css">
            <link rel="stylesheet" href="static/assets/css/flaticon.css">
            <link rel="stylesheet" href="static/assets/css/animate.min.css">
            <link rel="stylesheet" href="static/assets/css/magnific-popup.css">
            <link rel="stylesheet" href="static/assets/css/fontawesome-all.min.css">
            <link rel="stylesheet" href="static/assets/css/themify-icons.css">
            <link rel="stylesheet" href="static/assets/css/slick.css">
            <link rel="stylesheet" href="static/assets/css/nice-select.css">
            <link rel="stylesheet" href="static/assets/css/style.css">
   </head>

   <body>
    <!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="static/assets/img/logo/logo.png" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->
    <!-- Header Start -->
    <div class="header-area header-transparent">
            <div class="main-header  header-sticky">
                <div class="container-fluid">
                    <div class="row align-items-center">
                        <!-- Logo -->
                        <div class="col-xl-2 col-lg-2 col-md-1">
                            <div class="logo">
                                <a href="/index"><img src="static/assets/img/logo/logo.png" alt=""></a>
                            </div>
                        </div>
                        <div class="col-xl-10 col-lg-10 col-md-10">
                        <div class="menu-main d-flex align-items-center justify-content-end">
                            <!-- Main-menu -->
                            <div class="main-menu f-right d-none d-lg-block">
                                    <nav> 
                                        <ul id="navigation">  
                                            <li><a href="/index">Home</a></li>
                                            <li><a href="/services">Services</a></li>
<!--
                                            <li><a href="services.html">Services</a>
                                                <ul class="submenu">
                                                    <li><a href="elements.html">Element</a></li>
                                                    <li><a href="apply.html">Apply Now</a></li>
                                                </ul>
                                            </li>
-->
                                            <li><a href="/contact">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                                <div class="header-right-btn f-right d-none d-lg-block">
                                    <a href="#" class="btn header-btn">+254-780-333777 </a>
                                </div>
                            </div>
                            </div>   
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
    <!-- Header End -->
    <main>

        <!-- Hero Start-->
        <div class="hero-area2  slider-height2 hero-overly2 d-flex align-items-center ">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center pt-50">
                            <h2>About us</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--Hero End -->
        <!-- About Law Start-->
        <div class="about-low-area section-padding2">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-12">
                        <div class="about-caption mb-50">
                            <!-- Section Tittle -->
                            <div class="section-tittle mb-35">
                                <span>About Our Company</span>
                                <h2>Building a Brighter financial Future & Good Support.</h2>
                            </div>
                            <!-- <div class="card w-50">
                              <div class="card-body">
                                <h5 class="card-title" style="color: #3589f1;;">Our Goal</h5>
                                <p class="card-text" style="color: white;">To assist our customers to know their loan eligibility status, enabling them to make distinctive, lasting, and sizeable enhancements of their performance.</p>
                              </div>
                            </div> -->
                            <div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
                                <div class="card-body">
                                  <!-- <h5 class="card-title" style="color: #3589f1;;">Our Goal</h5> -->
                                  <h5 class="card-title" style="color: white;">Our Goal</h5>
                                <p class="card-text" style="color: white;">To assist our customers to know their loan eligibility status, enabling them to make distinctive, lasting, and sizeable enhancements of their performance.</p>
                                </div>
                              </div>
                            <p></p>
                            <a href="/sign-up" class="btn">Sign Up</a>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12">
                        <!-- about-img -->
                        <div class="about-img ">
                            <div class="about-font-img d-none d-lg-block">
                                <img src="static/assets/img/gallery/about2b.jpg"  alt="">
                            </div>
                            <div class="about-back-img ">
                                <img src="static/assets/img/gallery/about1c.jpg" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- About Law End-->
        <!-- Support Company Start-->
        <!-- Support Company End-->
        <!-- Application Area Start -->
        <!-- Application Area End -->
        <!--Team Ara Start -->
        
        <!-- Testimonial Start -->
        
        <!-- Testimonial End -->
        <!-- Blog Ara Start -->
        
        <!-- Blog Ara End -->

    </main>
    <footer>
        <!-- Footer Start-->
        <div class="footer-area">
            <div class="container">
               <div class="footer-top footer-padding">
                    <div class="row justify-content-between">
                        <div class="col-xl-3 col-lg-4 col-md-4 col-sm-6">
                            <div class="single-footer-caption mb-50">
                                <div class="single-footer-caption mb-30">
                                    <!-- logo -->
                                    <div class="footer-logo">
                                        <a href="/index"><img src="static/assets/img/logo/logo2_footer.png" alt=""></a>
                                    </div>
                                    <div class="footer-pera">
                                        <p>Invaluable financial planning at your fingertips.</p>
                                   </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-2 col-lg-2 col-md-4 col-sm-6">
                            <div class="single-footer-caption mb-50">
                                <div class="footer-tittle">
                                    <h4>Quick Link</h4>
                                    <ul>
                                        <li><a href="/about">About</a></li>
                                        <li><a href="/contact">Contact Us</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                            <div class="single-footer-caption mb-50">
                                <div class="footer-tittle">
                                    <h4>Support</h4>
                                    <ul>
                                        <li><a href="#">Frequently Asked Questions</a></li>
                                        <li><a href="#">Terms & Conditions</a></li>
                                        <li><a href="#"> Privacy Policy</a></li>
                                        <li><a href="#">Report a Payment Issue</a></li>     
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
               </div>
                <div class="footer-bottom">
                    <div class="row d-flex justify-content-between align-items-center">
                        <div class="col-xl-9 col-lg-8">
                            <div class="footer-copy-right">
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-4">
                            <!-- Footer Social -->
                            <div class="footer-social f-right">
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fab fa-facebook-f"></i></a>
                                <a href="#"><i class="fas fa-globe"></i></a>
                                <a href="#"><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                    </div>
               </div>
            </div>
        </div>
        <!-- Footer End-->
    </footer>
    <!-- Scroll Up -->
    <div id="back-top" >
        <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
    </div>


    <!-- JS here -->
		<!-- All JS Custom Plugins Link Here here -->
        <script src="./static/assets/js/vendor/modernizr-3.5.0.min.js"></script>
		<!-- Jquery, Popper, Bootstrap -->
		<script src="./static/assets/js/vendor/jquery-1.12.4.min.js"></script>
        <script src="./static/assets/js/popper.min.js"></script>
        <script src="./static/assets/js/bootstrap.min.js"></script>
	    <!-- Jquery Mobile Menu -->
        <script src="./static/assets/js/jquery.slicknav.min.js"></script>

		<!-- Jquery Slick , Owl-Carousel Plugins -->
        <script src="./static/assets/js/owl.carousel.min.js"></script>
        <script src="./static/assets/js/slick.min.js"></script>
		<!-- One Page, Animated-HeadLin -->
        <script src="./static/assets/js/wow.min.js"></script>
		<script src="./static/assets/js/animated.headline.js"></script>
        <script src="./static/assets/js/jquery.magnific-popup.js"></script>

		<!-- Nice-select, sticky -->
        <script src="./static/assets/js/jquery.nice-select.min.js"></script>
		<script src="./static/assets/js/jquery.sticky.js"></script>
        
        <!-- contact js -->
        <script src="./static/assets/js/contact.js"></script>
        <script src="./static/assets/js/jquery.form.js"></script>
        <script src="./static/assets/js/jquery.validate.min.js"></script>
        <script src="./static/assets/js/mail-script.js"></script>
        <script src="./static/assets/js/jquery.ajaxchimp.min.js"></script>
        
		<!-- Jquery Plugins, main Jquery -->	
        <script src="./static/assets/js/plugins.js"></script>
        <script src="./static/assets/js/main.js"></script>
        
    </body>
</html>

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="static/assets/css/loancalc.css" /> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

    <!-- Using Jinja templating engine -->
    <title>{% block title %}Home{% endblock %}</title> <!-- Defining a block in this base template that can be overriden in the child template -->
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbar"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav">
            {% if user.is_authenticated %} 
            <a class="nav-item nav-link" id="eligibility" href="/eligibility">Eligibility</a>
            <a class="nav-item nav-link" id="calculator" href="/loancalc">EMI Calculator</a>
            <a class="nav-item nav-link" id="home" href="/">Home</a>
            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
            {% else %}
            <a class="nav-item nav-link" id="index" href="/index">Welcome</a>
            <a class="nav-item nav-link" id="login" href="/login">Login</a>
            <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
            <a class="nav-item nav-link" id="about" href="/about">About</a>
            <a class="nav-item nav-link" id="contact" href="/contact">Contact</a>
            {% endif %}
          </div>
        </div>
      </nav>

      <!-- Showing the error and success message boxes -->
      {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %} {% if category ==
        'error' %}
        <div class="alert alert-danger alter-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}

      <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
      crossorigin="anonymous">
    </script>

    <!-- Script to reference an external file e.g. index.js in this case -->
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}" 
    ></script> <!-- You can write a python expression between the double curly brackets E.g. url for-->
    <script src="/static/assets/js/loancalc.js"></script>
</body>
</html>

website/templates/home.html
<!-- Extending the base template -->
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block content %}
<div class="row" style="margin-top: 50px;">
  <div class="col-sm-6">
    <div class="card text-white bg-primary mb-3">
      <div class="card-body">
        <h5 class="card-title" style="font-weight:700; font-size:large;">Loan Eligibility Check</h5>
        <p class="card-text" style="margin-top: 20px;">Know your eligibility beforehand</p>
        <a href="/eligibility" class="btn btn-primary" style="margin-top: 30px; background-color:#7CFC00;">Go</a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card text-white bg-primary mb-3">
      <div class="card-body">
        <h5 class="card-title" style="font-weight:700; font-size:large;">EMI Calculator</h5>
        <p class="card-text" style="margin-top: 20px;">Easily calculate your loan EMI</p>
        <a href="/loancalc" class="btn btn-primary" style="margin-top: 30px; background-color:#7CFC00;">Go</a>
      </div>
    </div>
  </div>
</div>
<!-- <h1 align="center">Notes</h1>
<ul class="list-group list-group-flush" id="notes">
  {% for note in user.notes %}
  <li class="list-group-item">{{ note.data }}
    <button type="button" class="close" onClick="deleteNote({{ note.id }})">
        <span aria-hidden="true">&times;</span>
      </button>
  </li>
  {% endfor %}
</ul>
<form method="POST">
  <textarea name="note" id="note" class="form-control"></textarea>
  <br />
  <div align="center">
    <button type="submit" class="btn btn-primary">Add Note</button>
  </div>
</form> -->
{% endblock %}

website/templates/loancalc.html
<!-- FOR EQUATED MONTHLY INSTALLMENT (EMI) -->
{% extends "base.html" %} {% block title %}Login{% endblock %}
{% block content %}
<head>
    <title>Loan Calculator</title>
    <link rel="stylesheet" href="static/assets/css/loancalc.css" />
</head>
<body>
    <div class="loan-calculator">
        <div class="top">
          <h2 id="work">Loan Calculator</h2>
  
          <form action="#">
            <div class="group">
              <div class="title">Amount</div>
              <input type="text" value="30000" class="loan-amount" />
            </div>
  
            <div class="group">
              <div class="title">Interest Rate</div>
              <input type="text" value="8.5" class="interest-rate" />
            </div>
  
            <div class="group">
              <div class="title">Tenure (in months)</div>
              <input type="text" value="240" class="loan-tenure" />
            </div>
          </form>
        </div>

        <div class="result">
            <div class="left">
              <div class="loan-emi">
                <h3>Loan EMI</h3>
                <div class="value">123</div>
              </div>
    
              <div class="total-interest">
                <h3>Total Interest Payable</h3>
                <div class="value">1234</div>
              </div>
    
              <div class="total-amount">
                <h3>Total Amount</h3>
                <div class="value">12345</div>
              </div>
    
              <button class="calculate-btn">Calculate</button>
            </div>
    
            <div class="right">
              <canvas id="myChart" width="400" height="400"></canvas>
            </div>
          </div>
        </div>
        
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.2/dist/chart.min.js"></script>
    <!-- <script src="loancalc.js"></script> -->
</body>
{% endblock %}

website/templates/login.html
<!-- Extending the base template -->
{% extends "base.html" %} {% block title %}Login{% endblock %}
{% block content %}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter email"
      />
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input
        type="password"
        class="form-control"
        id="password"
        name="password"
        placeholder="Enter password"
      />
    </div>
    <br />
    <!-- <button type="submit" class="btn btn-primary">Login</button> -->
    <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>
    <a href="/sign-up" class="link-primary" id="sign-link">Sign Up</a>
  </form> 
{% endblock %}

website/templates/predictionresult.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Result</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='assets/css2/bootstrap.min.css') }}" rel="stylesheet"> 
    <!-- Bootstrap theme -->
    <link href="{{ url_for('static', filename='assets/css2/bootstrap-theme.min.css') }}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='assets/css2/theme.css') }}" rel="stylesheet">

  </head>

  <body>

    <div class="container theme-showcase" role="main">

      <div class="jumbotron" style="color: rgb(0, 60, 255);">
        <h1>{{prediction_text}}</h1>
        
      </div>

      <div class="page-header">
        <!-- <h1>These are your details</h1> -->
      </div>
      <div class="well">
        <!-- Gender: {{gender}}
        Marital Status: {{married}}
        Dependents: {{dependents}}
        Education: {{education}}
        Credit: {{credit}}
        Area: {{area}}
        Applicant income: {{applicantincome}}
        Co-applicant income: {{coapplicantincome}}
        Loan Amount: {{loanamount}}
        Loan Amount Term: {{loanamountterm}} -->
        <a type="button" class="btn btn-link" href="{{ url_for('auth.home') }}">Back to</a>
      </div>

    </div> <!-- /container -->

  </body>
</html>